import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import os

# ==========================================
# PAGE CONFIGURATION
# ==========================================
st.set_page_config(
    page_title="Customer Segments",
    page_icon="pie_chart",
    layout="wide"
)

def load_css(css_file):
    if os.path.exists(css_file):
        with open(css_file) as f:
            st.markdown(f'<style>{f.read()}</style>', unsafe_allow_html=True)

load_css("assets/style.css")

# ==========================================
# CACHING DATA LOAD
# ==========================================
@st.cache_data
def load_data():
    filepath = "Data/processed/clustered_data.csv"
    if not os.path.exists(filepath):
        st.error(f"Dataset not found at {filepath}")
        return pd.DataFrame()
    return pd.read_csv(filepath)

# ==========================================
# MAIN PAGE CONTENT
# ==========================================
def main():
    st.title("🥧 Customer Segment Analysis")
    st.markdown("Dive deep into the characteristics of each customer segment identified by the K-Means clustering algorithm.")
    st.markdown("---")

    with st.spinner("Loading segmentation data..."):
        df = load_data()
        
    if df.empty:
        st.warning("No data available to display.")
        return
        
    # Ensure Cluster column exists
    if 'Cluster' not in df.columns:
        st.error("The dataset does not contain a 'Cluster' column.")
        return

    # Map Clusters to Names as requested
    cluster_map = {0: 'Regular Customers', 1: 'At-Risk Customers', 2: 'VIP Customers'}
    df['Segment_Name'] = df['Cluster'].map(lambda x: cluster_map.get(x, f"Cluster {x}"))
    
    # Extract RFM Columns gracefully
    r_col = 'Recency' if 'Recency' in df.columns else None
    f_col = 'Frequency' if 'Frequency' in df.columns else None
    m_col = 'Monetary' if 'Monetary' in df.columns else ('Total_Spend' if 'Total_Spend' in df.columns else None)
    
    # -----------------------------------------------------
    # SEGMENT DISTRIBUTION (PIE & BAR)
    # -----------------------------------------------------
    st.subheader("Segment Distribution")
    
    segment_counts = df['Segment_Name'].value_counts().reset_index()
    segment_counts.columns = ['Segment', 'Count']
    
    col1, col2 = st.columns(2)
    
    with col1:
        # Pie Chart
        fig_pie = px.pie(
            segment_counts, 
            names='Segment', 
            values='Count',
            title='Customer Distribution by Segment',
            color='Segment',
            color_discrete_map={
                'VIP Customers': '#2a9d8f', 
                'Regular Customers': '#e9c46a', 
                'At-Risk Customers': '#e76f51'
            },
            hole=0.4
        )
        fig_pie.update_layout(margin=dict(t=50, b=0, l=0, r=0))
        st.plotly_chart(fig_pie, use_container_width=True)
        
    with col2:
        # Bar Chart
        fig_bar = px.bar(
            segment_counts, 
            x='Segment', 
            y='Count',
            title='Customer Count by Segment',
            color='Segment',
            color_discrete_map={
                'VIP Customers': '#2a9d8f', 
                'Regular Customers': '#e9c46a', 
                'At-Risk Customers': '#e76f51'
            }
        )
        fig_bar.update_layout(margin=dict(t=50, b=0, l=0, r=0))
        st.plotly_chart(fig_bar, use_container_width=True)

    st.markdown("---")

    # -----------------------------------------------------
    # REVENUE BY SEGMENT
    # -----------------------------------------------------
    if m_col:
        st.subheader("Revenue by Segment")
        revenue_df = df.groupby('Segment_Name')[m_col].sum().reset_index()
        revenue_df.columns = ['Segment', 'Total Revenue']
        
        fig_revenue = px.bar(
            revenue_df, 
            x='Segment', 
            y='Total Revenue',
            title='Total Revenue Generated by Segment',
            color='Segment',
            color_discrete_map={
                'VIP Customers': '#2a9d8f', 
                'Regular Customers': '#e9c46a', 
                'At-Risk Customers': '#e76f51'
            },
            text_auto='.2s'
        )
        fig_revenue.update_layout(margin=dict(t=50, b=0, l=0, r=0))
        st.plotly_chart(fig_revenue, use_container_width=True)
    else:
        st.warning("Monetary feature missing from dataset. Cannot display revenue charts.")

    st.markdown("---")
    
    # -----------------------------------------------------
    # AVERAGE METRICS BY SEGMENT
    # -----------------------------------------------------
    st.subheader("Segment Comparison (Average Values)")
    
    # Group by segment and calculate means
    if r_col and f_col and m_col:
        avg_df = df.groupby('Segment_Name')[[r_col, f_col, m_col]].mean().reset_index()
        
        col_r, col_f, col_m = st.columns(3)
        
        with col_r:
            fig_r = px.bar(avg_df, x='Segment_Name', y=r_col, title="Avg Recency", color='Segment_Name',
                           color_discrete_map={'VIP Customers': '#2a9d8f', 'Regular Customers': '#e9c46a', 'At-Risk Customers': '#e76f51'})
            fig_r.update_layout(showlegend=False, margin=dict(t=40, b=0, l=0, r=0))
            st.plotly_chart(fig_r, use_container_width=True)
            
        with col_f:
            fig_f = px.bar(avg_df, x='Segment_Name', y=f_col, title="Avg Frequency", color='Segment_Name',
                           color_discrete_map={'VIP Customers': '#2a9d8f', 'Regular Customers': '#e9c46a', 'At-Risk Customers': '#e76f51'})
            fig_f.update_layout(showlegend=False, margin=dict(t=40, b=0, l=0, r=0))
            st.plotly_chart(fig_f, use_container_width=True)
            
        with col_m:
            fig_m = px.bar(avg_df, x='Segment_Name', y=m_col, title="Avg Monetary", color='Segment_Name',
                           color_discrete_map={'VIP Customers': '#2a9d8f', 'Regular Customers': '#e9c46a', 'At-Risk Customers': '#e76f51'})
            fig_m.update_layout(showlegend=False, margin=dict(t=40, b=0, l=0, r=0))
            st.plotly_chart(fig_m, use_container_width=True)
    else:
        st.warning("One or more RFM columns (Recency, Frequency, Monetary) are missing. Unable to compute averages.")

if __name__ == "__main__":
    main()
